/** @module config/env-registry — Environment variable registry and derived key sets. */
import type { EnvKeyMeta } from './types.js';

export const ENV_REGISTRY: Readonly<Record<string, EnvKeyMeta>> = {
  // ── Mode ──
  TOOL_AUTO_APPROVE_MODE: {
    cat: 'mode',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Global default for auto-approve mode. When true, MCP tool calls execute without user approval prompts. Per-session override via !autorun in Slack.',
    default: 'false',
    valueType: 'boolean',
  },

  // ── Messaging > Slack ──
  SLACK_BOT_TOKEN: {
    cat: 'messaging',
    sub: 'slack',
    mutable: false,
    sensitive: true,
    skill: false,
    editable: true,
    persistence: 'secure-store',
    scope: 'daemon',
    description:
      'Slack Bot User OAuth Token. Starts with xoxb-. Found in your Slack App > OAuth & Permissions.',
  },
  SLACK_APP_TOKEN: {
    cat: 'messaging',
    sub: 'slack',
    mutable: false,
    sensitive: true,
    skill: false,
    editable: true,
    persistence: 'secure-store',
    scope: 'daemon',
    description:
      'Slack App-Level Token for Socket Mode. Starts with xapp-. Found in your Slack App > Basic Information > App-Level Tokens.',
  },
  ALLOWED_USER_IDS: {
    cat: 'messaging',
    sub: 'slack',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Comma-separated Slack User IDs authorized to interact with the bot. Example: U01ABC123,U02DEF456',
  },
  ALLOWED_TEAM_ID: {
    cat: 'messaging',
    sub: 'slack',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Optional. Restrict access to a specific Slack Team (Workspace) ID. Leave empty to allow any workspace.',
  },

  // ── Apps > General ──
  DEFAULT_TOOL: {
    cat: 'apps',
    sub: 'general',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Default CLI tool for new sessions.',
    default: 'claude',
    valueType: 'enum',
    enumValues: ['claude', 'codex', 'gemini'],
  },

  // ── Apps > Claude ──
  ANTHROPIC_API_KEY: {
    cat: 'apps',
    sub: 'claude',
    mutable: true,
    sensitive: true,
    skill: false,
    editable: true,
    persistence: 'secure-store',
    scope: 'driver',
    description: 'Anthropic API key for Claude. Required unless using Bedrock/Vertex.',
  },
  CLAUDE_COMMAND: {
    cat: 'apps',
    sub: 'claude',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description: 'Path to the Claude CLI binary. Auto-detected from PATH if not set.',
  },
  CLAUDE_MODEL: {
    cat: 'apps',
    sub: 'claude',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      'Default model for Claude sessions. Examples: opus, claude-opus-4-6. Leave empty for CLI default.',
  },
  CLAUDE_DEFAULT_MODE: {
    cat: 'apps',
    sub: 'claude',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Default mode for new Claude sessions. write allows file edits. readonly restricts to read-only operations.',
    default: 'write',
    valueType: 'mode',
  },
  CLAUDE_READONLY_PERMISSION_MODE: {
    cat: 'apps',
    sub: 'claude',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      "Permission mode for read-only sessions. default uses Claude's default mode. plan restricts to planning only.",
    valueType: 'enum',
    enumValues: ['default', 'plan'],
  },
  CLAUDE_MCP_AUTH_SERVER: {
    cat: 'apps',
    sub: 'claude',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'MCP server name that requires OAuth authentication preflight. Leave empty to skip MCP auth checks.',
  },
  CLAUDE_MCP_CONFIG_PATH: {
    cat: 'apps',
    sub: 'claude',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      'Path to the global Claude MCP config file used for server import. HuskyGate-managed runs generate a strict config under <workdir>/.huskygate/.',
  },

  // ── Apps > Gemini ──
  GEMINI_API_KEY: {
    cat: 'apps',
    sub: 'gemini',
    mutable: true,
    sensitive: true,
    skill: false,
    editable: true,
    persistence: 'secure-store',
    scope: 'driver',
    description: 'Gemini API key. Required unless GOOGLE_API_KEY is set.',
  },
  GOOGLE_API_KEY: {
    cat: 'apps',
    sub: 'gemini',
    mutable: true,
    sensitive: true,
    skill: false,
    editable: true,
    persistence: 'secure-store',
    scope: 'driver',
    description:
      'Google API key (alternative to GEMINI_API_KEY). Used as fallback for Gemini authentication.',
  },
  GEMINI_COMMAND: {
    cat: 'apps',
    sub: 'gemini',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description: 'Path to the Gemini CLI binary. Auto-detected from PATH if not set.',
  },
  GEMINI_MODEL: {
    cat: 'apps',
    sub: 'gemini',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      'Default model for Gemini sessions. Example: gemini-2.5-pro. Leave empty for CLI default.',
  },
  GEMINI_DEFAULT_MODE: {
    cat: 'apps',
    sub: 'gemini',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Default mode for new Gemini sessions. write allows file edits. readonly restricts to read-only operations.',
    default: 'write',
    valueType: 'mode',
  },
  GEMINI_READONLY_APPROVAL_MODE: {
    cat: 'apps',
    sub: 'gemini',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      "Approval mode for read-only sessions. default uses Gemini's default mode. plan restricts to planning only.",
    valueType: 'enum',
    enumValues: ['default', 'plan'],
  },
  GEMINI_MCP_AUTH_SERVER: {
    cat: 'apps',
    sub: 'gemini',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'MCP server name that requires authentication. Leave empty to disable.',
  },
  GEMINI_MCP_CONFIG_PATH: {
    cat: 'apps',
    sub: 'gemini',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      'Path to the Gemini MCP config file. Absolute or relative to $HOME. Default: ~/.gemini/settings.json',
  },

  // ── Apps > Codex ──
  OPENAI_API_KEY: {
    cat: 'apps',
    sub: 'codex',
    mutable: true,
    sensitive: true,
    skill: false,
    editable: true,
    persistence: 'secure-store',
    scope: 'driver',
    description: 'OpenAI API key for Codex. Required unless CODEX_HOME is configured.',
  },
  CODEX_COMMAND: {
    cat: 'apps',
    sub: 'codex',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      'Path to the Codex CLI binary. Auto-detected from PATH or /Applications/Codex.app bundle if not set.',
  },
  CODEX_MODEL: {
    cat: 'apps',
    sub: 'codex',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description: 'Default model for Codex sessions. Example: o3. Leave empty for CLI default.',
  },
  CODEX_MCP_AUTH_SERVER: {
    cat: 'apps',
    sub: 'codex',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'MCP server name for authentication preflight. Runs codex mcp login <server> before execution. Leave empty to disable.',
  },
  CODEX_MCP_CONFIG_PATH: {
    cat: 'apps',
    sub: 'codex',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      'Path to the Codex MCP config file. Absolute or relative to $HOME. Default: ~/.codex/config.toml',
  },
  CODEX_DEFAULT_SANDBOX_MODE: {
    cat: 'apps',
    sub: 'codex',
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Default sandbox mode for new Codex sessions. write fully bypasses OS-level sandbox. readonly blocks file writes and network access. Per-session override: !mode=write / !mode=readonly.',
    default: 'write',
    valueType: 'mode',
  },

  // ── Environment > Runtime ──
  MAX_CONCURRENCY: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Maximum number of CLI jobs running simultaneously across all sessions.',
    default: '2',
    valueType: 'positiveInt',
  },
  MAX_RUNTIME_SEC: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Maximum wall-clock time (seconds) per job before it is forcefully stopped.',
    default: '900',
    valueType: 'positiveInt',
  },
  NO_OUTPUT_TIMEOUT_SEC: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Seconds of no stdout output before a job is considered stalled. Retries up to 3 times before killing.',
    default: '90',
    valueType: 'positiveInt',
  },
  WORKDIR_ROOT: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Root directory where session working directories are created.',
    default: './workdir',
  },
  ALLOWED_WORKDIR_ROOTS: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Comma-separated absolute paths allowed as custom workdir targets (via workdir=/path). Default: same as WORKDIR_ROOT.',
  },
  LOG_LEVEL: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Logging verbosity.',
    default: 'info',
    valueType: 'enum',
    enumValues: ['debug', 'info', 'warn', 'error'],
  },
  SERVER_API_PORT: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Port for the internal Server API (bound to 127.0.0.1).',
    default: '3738',
    valueType: 'positiveInt',
    maxValue: 65535,
  },
  SERVER_API_HOST: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Host address that the internal Server API binds to. Keep local unless intentionally exposing the API.',
    default: '127.0.0.1',
  },
  WEBHOOK_PUBLIC_BASE_URL: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Public base URL for webhook endpoint URLs in the dashboard. Example: https://automation.example.com. Leave empty to show only the local path.',
  },
  CLOUDFLARE_TUNNEL_ENABLED: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Enable Cloudflare Tunnel for secure webhook ingress. Requires cloudflared CLI installed.',
    default: 'false',
    valueType: 'boolean',
  },
  CLOUDFLARE_TUNNEL_TOKEN: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: true,
    skill: false,
    editable: true,
    persistence: 'secure-store',
    scope: 'system',
    description:
      'Cloudflare Tunnel token for named tunnels (production). Leave empty to use quick tunnels (trycloudflare.com, development only).',
  },
  GITHUB_WEBHOOK_IP_ALLOWLIST: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Enable IP allowlisting for GitHub webhook endpoints using the GitHub Meta API. Defense-in-depth layer on top of HMAC signature verification.',
    default: 'true',
    valueType: 'boolean',
  },
  HUSKYGATE_DASHBOARD_COOKIE_SECURE: {
    cat: 'environment',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Set the Secure flag on the dashboard auth cookie. Enable (true) when serving behind a TLS-terminating reverse proxy. Default false for localhost HTTP.',
    default: 'false',
    valueType: 'boolean',
  },
  HUSKYGATE_LOG_STACKS: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Include stack traces in log output even when log level is above debug.',
    default: 'false',
    valueType: 'boolean',
  },

  // ── Internal (auto-generated, not editable) ──
  SERVER_API_SECRET: {
    cat: 'internal',
    sub: null,
    mutable: false,
    sensitive: true,
    skill: false,
    editable: false,
    persistence: 'generated',
    scope: 'daemon',
  },
  DASHBOARD_SECRET: {
    cat: 'internal',
    sub: null,
    mutable: false,
    sensitive: true,
    skill: false,
    editable: false,
    persistence: 'generated',
    scope: 'daemon',
  },

  // ── Environment > Skills ──
  PERPLEXITY_API_KEY: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: true,
    skill: true,
    editable: true,
    persistence: 'secure-store',
    scope: 'skill',
    description: 'Perplexity API key. Required when the Perplexity skill is enabled.',
  },
  AWS_ACCESS_KEY_ID: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: true,
    skill: true,
    editable: true,
    persistence: 'secure-store',
    scope: 'skill',
    description: 'AWS Access Key ID. Required when the AWS CLI skill is enabled.',
  },
  AWS_SECRET_ACCESS_KEY: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: true,
    skill: true,
    editable: true,
    persistence: 'secure-store',
    scope: 'skill',
    description: 'AWS Secret Access Key. Required when the AWS CLI skill is enabled.',
  },
  AWS_DEFAULT_REGION: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: true,
    editable: true,
    persistence: 'config-db',
    scope: 'skill',
    description: 'AWS default region. Example: ap-northeast-1. Used by the AWS CLI skill.',
  },

  AZURE_CLIENT_ID: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: true,
    skill: true,
    editable: true,
    persistence: 'secure-store',
    scope: 'skill',
    description: 'Azure AD application (client) ID for service principal authentication.',
  },
  AZURE_CLIENT_SECRET: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: true,
    skill: true,
    editable: true,
    persistence: 'secure-store',
    scope: 'skill',
    description: 'Azure AD client secret for service principal authentication.',
  },
  AZURE_TENANT_ID: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: true,
    editable: true,
    persistence: 'config-db',
    scope: 'skill',
    description: 'Azure AD tenant (directory) ID.',
  },
  AZURE_SUBSCRIPTION_ID: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: true,
    editable: true,
    persistence: 'config-db',
    scope: 'skill',
    description: 'Azure subscription ID. Used as default for Azure CLI commands.',
  },

  GOOGLE_APPLICATION_CREDENTIALS: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: true,
    skill: true,
    editable: true,
    persistence: 'secure-store',
    scope: 'skill',
    description: 'Path to the GCP service account key JSON file.',
  },
  CLOUDSDK_CORE_PROJECT: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: true,
    editable: true,
    persistence: 'config-db',
    scope: 'skill',
    description: 'Default GCP project ID for gcloud commands.',
  },
  HUSKYGATE_OAUTH_TRUSTED_HOSTS: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'driver',
    description:
      'Comma-separated hostnames trusted for OAuth callback redirects. Used by MCP OAuth preflight.',
  },

  // ── Environment > Session & Schedule ──
  SESSION_IDLE_TIMEOUT_SEC: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Seconds of inactivity before a Slack session is automatically exited. Default: 86400 (24 hours).',
    default: '86400',
    valueType: 'positiveInt',
  },
  SESSION_CLEANUP_ENABLED: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Enable automatic cleanup of idle sessions.',
    default: 'true',
    valueType: 'boolean',
  },
  SCHEDULE_ENABLED: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Enable the schedule engine (cron-based job execution).',
    default: 'true',
    valueType: 'boolean',
  },
  SCHEDULE_POLL_INTERVAL_SEC: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Polling interval (seconds) for the scheduler to check due jobs.',
    default: '30',
    valueType: 'positiveInt',
  },
  SCHEDULE_MAX_CONCURRENT: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description: 'Maximum number of scheduled jobs running concurrently.',
    default: '1',
    valueType: 'positiveInt',
  },
  SCHEDULE_DEFAULT_NOTIFY_CHANNEL: {
    cat: 'environment',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: false,
    editable: true,
    persistence: 'config-db',
    scope: 'system',
    description:
      'Slack channel ID for schedule execution notifications. Leave empty to notify in the original channel.',
  },

  // ── Internal (derived, not editable) ──
  HUSKYGATE_API_BASE: {
    cat: 'internal',
    sub: null,
    mutable: true,
    sensitive: false,
    skill: true,
    editable: false,
    persistence: 'derived',
    scope: 'skill',
  },
  HUSKYGATE_API_SECRET: {
    cat: 'internal',
    sub: null,
    mutable: true,
    sensitive: true,
    skill: true,
    editable: false,
    persistence: 'derived',
    scope: 'skill',
  },
  SKILL_TEMPLATE_DIR: {
    cat: 'internal',
    sub: null,
    mutable: false,
    sensitive: false,
    skill: false,
    editable: false,
    persistence: 'env-only',
    scope: 'system',
  },
};

export const KNOWN_ENV_KEYS: ReadonlySet<string> = new Set(Object.keys(ENV_REGISTRY));
export const SETTINGS_EDITABLE_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.editable)
    .map(([key]) => key),
);
export const PERSISTED_CONFIG_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.persistence === 'config-db')
    .map(([key]) => key),
);
export const SECURE_STORE_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.persistence === 'secure-store')
    .map(([key]) => key),
);
export const MANAGED_PERSISTED_KEYS: ReadonlySet<string> = new Set(
  [...SETTINGS_EDITABLE_KEYS].filter(
    (key) => PERSISTED_CONFIG_KEYS.has(key) || SECURE_STORE_KEYS.has(key),
  ),
);
export const RUNTIME_MUTABLE_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.mutable)
    .map(([key]) => key),
);
export const SKILL_ENV_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.skill)
    .map(([key]) => key),
);
export const PROCESS_ENV_SYNC_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.skill || meta.scope === 'driver')
    .map(([key]) => key),
);
export const HOT_PROCESS_ENV_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.mutable && (meta.skill || meta.scope === 'driver'))
    .map(([key]) => key),
);
export const HOT_RELOADABLE_KEYS: ReadonlySet<string> = new Set([
  ...HOT_PROCESS_ENV_KEYS,
  'LOG_LEVEL',
  'MAX_CONCURRENCY',
  'MAX_RUNTIME_SEC',
  'NO_OUTPUT_TIMEOUT_SEC',
  'SESSION_IDLE_TIMEOUT_SEC',
  'TOOL_AUTO_APPROVE_MODE',
  'HUSKYGATE_LOG_STACKS',
]);

/** Keys whose values must be stored in the OS keychain, never in plaintext config. */
export const SENSITIVE_KEYS: ReadonlySet<string> = new Set(
  Object.entries(ENV_REGISTRY)
    .filter(([, meta]) => meta.sensitive)
    .map(([key]) => key),
);
