/** @module runner/types — Shared interfaces for driver implementations and run results. */
import type { ToolName } from '../config.js';
import type { Mode, Session, ToolState } from '../session/types.js';

/** Normalized event emitted by any driver during a run. */
export interface DriverEvent {
  type: 'text' | 'tool_use' | 'tool_result' | 'error' | 'status' | 'done';
  content: string;
  /**
   * Tool call arguments (only set on `tool_use` announcement events).
   * Contains the full input/args of the tool call for display purposes.
   * NOT set on streaming delta events (e.g. `input_json_delta`).
   */
  toolInput?: unknown;
  raw?: unknown;
}

export interface DriverBuildOptions {
  autoApproveEnabled: boolean;
  skillsEnabled: boolean;
  /**
   * Whether MCP tools are allowed for this execution.
   * When false, drivers must not inject MCP tool globs (mcp__*, mcp_*).
   * Defaults to true when not set (backward compat for chat sessions).
   */
  allowMcp?: boolean;
  /**
   * Tool-specific MCP configuration file generated by HuskyGate for this run.
   * Drivers that support explicit config injection should prefer this path over
   * ambient user/project config to avoid cross-session interference.
   */
  mcpConfigPath?: string | null;
}

/** Contract that each CLI driver (Claude, Codex, Gemini) must implement. */
export interface Driver {
  readonly name: ToolName;
  buildCommand(): string;
  buildArgs(prompt: string, session: Session, mode: Mode, options: DriverBuildOptions): string[];
  buildEnv(): Record<string, string>;
  parseEvent(line: string): DriverEvent | null;
  parseStderr(line: string): DriverEvent | null;
  extractSessionState(events: DriverEvent[]): ToolState;
}

/** Outcome of a single driver process execution. */
export interface RunResult {
  exitCode: number | null;
  events: DriverEvent[];
  errorKind: string | null;
  eventsDropped?: boolean;
}

/**
 * Raw event types that aggregate/summarize already-streamed text.
 *
 * Claude emits text via `content_block_delta` deltas, then a `result` event
 * containing the same text.  Codex emits `response.output_text.delta` deltas,
 * then `response.output_text.done`, `turn.completed`, etc. with the same text.
 *
 * These should be **filtered from real-time streams** (SSE/Slack) to avoid
 * duplication, but kept in `allEvents[]` for `extractAnswerText()` fallback
 * when no deltas were emitted.
 */
export const AGGREGATE_TEXT_RAW_TYPES: ReadonlySet<string> = new Set([
  'result', // Claude: final result after text deltas
  'response.output_text.done', // Codex: aggregated text after deltas
  'turn.completed', // Codex: turn summary
  'response.output_item.done', // Codex: item-level summary
  'response.completed', // Codex: response-level summary
]);

/** Check if a text event is an aggregate/summary that duplicates streamed deltas. */
export function isAggregateTextEvent(event: DriverEvent): boolean {
  if (event.type !== 'text') return false;
  const raw = event.raw as Record<string, unknown> | undefined;
  const rawType = raw?.type as string | undefined;
  return rawType !== undefined && AGGREGATE_TEXT_RAW_TYPES.has(rawType);
}
